name: Build LogME

on:
  push

permissions:
  contents: write
  pull-requests: write

jobs:
  build-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies for Node.js
        run: cd web-ui && npm install
      - name: Build Web-UI
        run: cd web-ui && npm run build
      - name: esp-idf-logme build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0
          target: esp32
          path: './'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LogME
          path: ./build