name: Build LogME

on: push

permissions:
  contents: write
  pull-requests: write

jobs:
  build-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies for Node.js
        run: cd web-ui && npm install
      - name: Build Web-UI
        run: cd web-ui && npm run build
      - name: esp-idf-logme build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0
          target: esp32
          path: './'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LogME
          path: ./build
  
  create-project:
    runs-on: ubuntu-latest
    needs: build-project
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: LogME
      - name: Archive Project
        uses: thedoctor0/zip-release@master
        with:
          filename: LogME.zip
      - name: Create Github-Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number}}
          release_name: Release ${{ github.run_number}}
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./LogME.zip
          asset_name: site-v${{ github.run_number }}.zip
      - name: Upload release binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: LogME/*/*.bin
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}